FROM node:alpine
# RUN npm install -g --force yarn
WORKDIR /var/www/
COPY . .
# # serve
# EXPOSE 8080
# CMD npm install ; npm run serve

# build
CMD yarn ; yarn build # ; tail -f /dev/null

# # reverse proxy
# RUN npm install
# EXPOSE 8080
# CMD [ "npm", "run", "serve" ]
